privateNodes:
  enabled: true
  vpn:
    enabled: true
    nodeToNode:
      enabled: false

controlPlane:
  distro:
    k8s:
      image:
        tag: v1.36.0
  coredns:
    embedded: false
  statefulSet:
    persistence:
      volumeClaim:
        enabled: true

networking:
  podCIDR: 10.65.0.0/16
  serviceCIDR: 10.129.0.0/16

deploy:
  cni:
    flannel:
      enabled: true
  kubeProxy:
    enabled: true
  localPathProvisioner:
    enabled: true
    nodePath: /var/lib/local-path-provisioner
