---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-admission
rules:
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - resourcequotas
  verbs:
  - get
