---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-admission
  namespace: tenant-database-gates
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - update
  - patch
