---
apiVersion: v1
kind: Service
metadata:
  name: database-admission
  namespace: tenant-system
spec:
  ports:
  - name: https
    port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: database-admission
