---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: tenant-system/database-admission-ca
  name: database-admission
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: database-admission
      namespace: tenant-system
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: tenantdatabases.tenancy.cnpg-vcluster.io
  rules:
  - apiGroups:
    - tenancy.cnpg-vcluster.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - tenantdatabases
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 30
