//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerVolumeIdentity) DeepCopyInto(out *DockerVolumeIdentity) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerVolumeIdentity.
func (in *DockerVolumeIdentity) DeepCopy() *DockerVolumeIdentity {
	if in == nil {
		return nil
	}
	out := new(DockerVolumeIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointAllocationIdentity) DeepCopyInto(out *EndpointAllocationIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointAllocationIdentity.
func (in *EndpointAllocationIdentity) DeepCopy() *EndpointAllocationIdentity {
	if in == nil {
		return nil
	}
	out := new(EndpointAllocationIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationResourceIdentity) DeepCopyInto(out *FoundationResourceIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationResourceIdentity.
func (in *FoundationResourceIdentity) DeepCopy() *FoundationResourceIdentity {
	if in == nil {
		return nil
	}
	out := new(FoundationResourceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundationSnapshot) DeepCopyInto(out *FoundationSnapshot) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]FoundationResourceIdentity, len(*in))
		copy(*out, *in)
	}
	if in.PeerAllocations != nil {
		in, out := &in.PeerAllocations, &out.PeerAllocations
		*out = make(map[string]EndpointAllocationIdentity, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundationSnapshot.
func (in *FoundationSnapshot) DeepCopy() *FoundationSnapshot {
	if in == nil {
		return nil
	}
	out := new(FoundationSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionalEvidence) DeepCopyInto(out *FunctionalEvidence) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionalEvidence.
func (in *FunctionalEvidence) DeepCopy() *FunctionalEvidence {
	if in == nil {
		return nil
	}
	out := new(FunctionalEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedResourceIdentity) DeepCopyInto(out *ObservedResourceIdentity) {
	*out = *in
	if in.PreviousUIDs != nil {
		in, out := &in.PreviousUIDs, &out.PreviousUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedResourceIdentity.
func (in *ObservedResourceIdentity) DeepCopy() *ObservedResourceIdentity {
	if in == nil {
		return nil
	}
	out := new(ObservedResourceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SurvivorSnapshot) DeepCopyInto(out *SurvivorSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SurvivorSnapshot.
func (in *SurvivorSnapshot) DeepCopy() *SurvivorSnapshot {
	if in == nil {
		return nil
	}
	out := new(SurvivorSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeardownStatus) DeepCopyInto(out *TeardownStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeardownStatus.
func (in *TeardownStatus) DeepCopy() *TeardownStatus {
	if in == nil {
		return nil
	}
	out := new(TeardownStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tenant) DeepCopyInto(out *Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tenant.
func (in *Tenant) DeepCopy() *Tenant {
	if in == nil {
		return nil
	}
	out := new(Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantList) DeepCopyInto(out *TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantList.
func (in *TenantList) DeepCopy() *TenantList {
	if in == nil {
		return nil
	}
	out := new(TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantSpec) DeepCopyInto(out *TenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantSpec.
func (in *TenantSpec) DeepCopy() *TenantSpec {
	if in == nil {
		return nil
	}
	out := new(TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantStatus) DeepCopyInto(out *TenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedResources != nil {
		in, out := &in.ObservedResources, &out.ObservedResources
		*out = make([]ObservedResourceIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TenantResources != nil {
		in, out := &in.TenantResources, &out.TenantResources
		*out = make([]ObservedResourceIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DockerVolume != nil {
		in, out := &in.DockerVolume, &out.DockerVolume
		*out = new(DockerVolumeIdentity)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkerContainers != nil {
		in, out := &in.WorkerContainers, &out.WorkerContainers
		*out = make([]WorkerContainerEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SurvivorSnapshots != nil {
		in, out := &in.SurvivorSnapshots, &out.SurvivorSnapshots
		*out = make([]SurvivorSnapshot, len(*in))
		copy(*out, *in)
	}
	if in.FoundationSnapshot != nil {
		in, out := &in.FoundationSnapshot, &out.FoundationSnapshot
		*out = new(FoundationSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionalEvidence != nil {
		in, out := &in.FunctionalEvidence, &out.FunctionalEvidence
		*out = new(FunctionalEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.Teardown != nil {
		in, out := &in.Teardown, &out.Teardown
		*out = new(TeardownStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantStatus.
func (in *TenantStatus) DeepCopy() *TenantStatus {
	if in == nil {
		return nil
	}
	out := new(TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerContainerEvidence) DeepCopyInto(out *WorkerContainerEvidence) {
	*out = *in
	if in.PreviousIDs != nil {
		in, out := &in.PreviousIDs, &out.PreviousIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImportedImages != nil {
		in, out := &in.ImportedImages, &out.ImportedImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerContainerEvidence.
func (in *WorkerContainerEvidence) DeepCopy() *WorkerContainerEvidence {
	if in == nil {
		return nil
	}
	out := new(WorkerContainerEvidence)
	in.DeepCopyInto(out)
	return out
}
