apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tenant-a-postgres
  namespace: database
  labels:
    io.cnpg-vcluster.kamaji-lab: kamaji-cnpg-tenants
    kamaji.cnpg-vcluster.io/tenant: tenant-a
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie@sha256:42708a75345b7a48fdd9257b071830783a97fd228529196b6313187a7198e185
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  bootstrap:
    initdb:
      database: tenant_a
      owner: tenant_a_owner
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
