apiVersion: v1
kind: Service
metadata:
  name: tenant-controller-webhook
  namespace: tenant-system
spec:
  selector:
    app.kubernetes.io/name: tenant-controller
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
