apiVersion: v1
kind: Namespace
metadata:
  name: kamaji-tenant-b
  labels:
    ${OWNERSHIP_LABEL}: ${LAB_PREFIX}
    kamaji.cnpg-vcluster.io/tenant: tenant-b
---
apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
metadata:
  name: tenant-b
  namespace: kamaji-tenant-b
  labels:
    ${OWNERSHIP_LABEL}: ${LAB_PREFIX}
    kamaji.cnpg-vcluster.io/tenant: tenant-b
spec:
  controlPlane:
    deployment:
      replicas: 1
      resources:
        apiServer:
          requests:
            cpu: ${TENANT_API_SERVER_REQUEST_CPU}
            memory: ${TENANT_API_SERVER_REQUEST_MEMORY}
          limits:
            cpu: ${TENANT_API_SERVER_LIMIT_CPU}
            memory: ${TENANT_API_SERVER_LIMIT_MEMORY}
        controllerManager:
          requests:
            cpu: ${TENANT_CONTROLLER_MANAGER_REQUEST_CPU}
            memory: ${TENANT_CONTROLLER_MANAGER_REQUEST_MEMORY}
          limits:
            cpu: ${TENANT_CONTROLLER_MANAGER_LIMIT_CPU}
            memory: ${TENANT_CONTROLLER_MANAGER_LIMIT_MEMORY}
        scheduler:
          requests:
            cpu: ${TENANT_SCHEDULER_REQUEST_CPU}
            memory: ${TENANT_SCHEDULER_REQUEST_MEMORY}
          limits:
            cpu: ${TENANT_SCHEDULER_LIMIT_CPU}
            memory: ${TENANT_SCHEDULER_LIMIT_MEMORY}
    service:
      serviceType: LoadBalancer
      allocateLoadBalancerNodePorts: false
      additionalMetadata:
        annotations:
          metallb.io/loadBalancerIPs: ${TENANT_B_VIP}
  kubernetes:
    version: ${KUBERNETES_VERSION}
    kubelet:
      preferredAddressTypes:
        - InternalIP
        - ExternalIP
      configurationJSONPatches:
        - op: add
          path: /cgroupDriver
          value: systemd
  networkProfile:
    address: ${TENANT_B_VIP}
    advertiseAddress: ${TENANT_B_VIP}
    port: 6443
    certSANs:
      - ${TENANT_B_VIP}
      - tenant-b
      - api.tenant-b.kamaji.local
    clusterDomain: tenant-b.cluster.local
    serviceCidrs:
      - 10.129.0.0/16
    podCidrs:
      - 10.65.0.0/16
    dnsServiceIPs:
      - 10.129.0.10
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity:
      server:
        image: ${KONNECTIVITY_SERVER_REPOSITORY}
        version: ${KONNECTIVITY_SERVER_VERSION_DIGEST}
        port: 8132
      agent:
        image: ${KONNECTIVITY_AGENT_REPOSITORY}
        version: ${KONNECTIVITY_AGENT_VERSION_DIGEST}
        mode: DaemonSet
        hostNetwork: true
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          - key: node.kubernetes.io/not-ready
            operator: Exists
            effect: NoSchedule
          - key: node.kubernetes.io/not-ready
            operator: Exists
            effect: NoExecute
  dataStore: default
  dataStoreSchema: kamaji-tenant-b
  dataStoreUsername: kamaji-tenant-b
