---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-controller-role
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenantdatabases
  verbs:
  - delete
  - list
  - watch
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - devclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - kamajicontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kubeadmconfigtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - devmachinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinesets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - devmachines
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - kubeadmconfigs
  verbs:
  - get
  - list
- apiGroups:
  - kamaji.clastix.io
  resources:
  - tenantcontrolplanes
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - watch
