---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenant-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - tenancy.cnpg-vcluster.io
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
